#!/bin/bash
#SBATCH --job-name="MPI_HelloWorld"
#SBATCH --workdir=.
#SBATCH --output=output_%J.out
#SBATCH --error=output_%J.err
#SBATCH --ntasks=16
#SBATCH --tasks-per-node=8
#SBATCH --time=00:01:00
#SBATCH --exclusive
#SBATCH --qos=debug

mpirun ./mpi_helloworld

